### ISSUE TITLE
Migrar Fotos e Vídeos

### ISSUE THREAD

**Issue by robertoosantos** [otavioalfenas/RespireFundo#1]
Por que não migrar as fotos e vídeos para um Google Drive ou Youtube?

Estando no repositório, o tempo de clone e fetch ficam muito altos.

https://help.github.com/en/github/managing-large-files/working-with-large-files

**Comment by otavioalfenas** [comment]
Codigo Atualizado.
Segregado imagens e estrutura do projeto para um Drive.
